/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseExplorerRealdataRouteImport } from './routes/universe-explorer-realdata'
import { Route as StyleLabRouteImport } from './routes/style-lab'
import { Route as GameColonyColonyIdRouteImport } from './routes/game/colony/$colonyId'
import { Route as GameColonyColonyIdResourcesRouteImport } from './routes/game/colony/$colonyId/resources'

const UniverseExplorerRealdataRoute =
  UniverseExplorerRealdataRouteImport.update({
    id: '/universe-explorer-realdata',
    path: '/universe-explorer-realdata',
    getParentRoute: () => rootRouteImport,
  } as any)
const StyleLabRoute = StyleLabRouteImport.update({
  id: '/style-lab',
  path: '/style-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GameColonyColonyIdRoute = GameColonyColonyIdRouteImport.update({
  id: '/game/colony/$colonyId',
  path: '/game/colony/$colonyId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameColonyColonyIdResourcesRoute =
  GameColonyColonyIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/style-lab': typeof StyleLabRoute
  '/universe-explorer-realdata': typeof UniverseExplorerRealdataRoute
  '/game/colony/$colonyId': typeof GameColonyColonyIdRouteWithChildren
  '/game/colony/$colonyId/resources': typeof GameColonyColonyIdResourcesRoute
}
export interface FileRoutesByTo {
  '/style-lab': typeof StyleLabRoute
  '/universe-explorer-realdata': typeof UniverseExplorerRealdataRoute
  '/game/colony/$colonyId': typeof GameColonyColonyIdRouteWithChildren
  '/game/colony/$colonyId/resources': typeof GameColonyColonyIdResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/style-lab': typeof StyleLabRoute
  '/universe-explorer-realdata': typeof UniverseExplorerRealdataRoute
  '/game/colony/$colonyId': typeof GameColonyColonyIdRouteWithChildren
  '/game/colony/$colonyId/resources': typeof GameColonyColonyIdResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/style-lab'
    | '/universe-explorer-realdata'
    | '/game/colony/$colonyId'
    | '/game/colony/$colonyId/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/style-lab'
    | '/universe-explorer-realdata'
    | '/game/colony/$colonyId'
    | '/game/colony/$colonyId/resources'
  id:
    | '__root__'
    | '/style-lab'
    | '/universe-explorer-realdata'
    | '/game/colony/$colonyId'
    | '/game/colony/$colonyId/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StyleLabRoute: typeof StyleLabRoute
  UniverseExplorerRealdataRoute: typeof UniverseExplorerRealdataRoute
  GameColonyColonyIdRoute: typeof GameColonyColonyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe-explorer-realdata': {
      id: '/universe-explorer-realdata'
      path: '/universe-explorer-realdata'
      fullPath: '/universe-explorer-realdata'
      preLoaderRoute: typeof UniverseExplorerRealdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-lab': {
      id: '/style-lab'
      path: '/style-lab'
      fullPath: '/style-lab'
      preLoaderRoute: typeof StyleLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/colony/$colonyId': {
      id: '/game/colony/$colonyId'
      path: '/game/colony/$colonyId'
      fullPath: '/game/colony/$colonyId'
      preLoaderRoute: typeof GameColonyColonyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/colony/$colonyId/resources': {
      id: '/game/colony/$colonyId/resources'
      path: '/resources'
      fullPath: '/game/colony/$colonyId/resources'
      preLoaderRoute: typeof GameColonyColonyIdResourcesRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
  }
}

interface GameColonyColonyIdRouteChildren {
  GameColonyColonyIdResourcesRoute: typeof GameColonyColonyIdResourcesRoute
}

const GameColonyColonyIdRouteChildren: GameColonyColonyIdRouteChildren = {
  GameColonyColonyIdResourcesRoute: GameColonyColonyIdResourcesRoute,
}

const GameColonyColonyIdRouteWithChildren =
  GameColonyColonyIdRoute._addFileChildren(GameColonyColonyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StyleLabRoute: StyleLabRoute,
  UniverseExplorerRealdataRoute: UniverseExplorerRealdataRoute,
  GameColonyColonyIdRoute: GameColonyColonyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
