/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseExplorerRouteImport } from './routes/universe-explorer'
import { Route as GravityDemoRouteImport } from './routes/gravity-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const UniverseExplorerRoute = UniverseExplorerRouteImport.update({
  id: '/universe-explorer',
  path: '/universe-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GravityDemoRoute = GravityDemoRouteImport.update({
  id: '/gravity-demo',
  path: '/gravity-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gravity-demo': typeof GravityDemoRoute
  '/universe-explorer': typeof UniverseExplorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gravity-demo': typeof GravityDemoRoute
  '/universe-explorer': typeof UniverseExplorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gravity-demo': typeof GravityDemoRoute
  '/universe-explorer': typeof UniverseExplorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/gravity-demo' | '/universe-explorer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/gravity-demo' | '/universe-explorer'
  id: '__root__' | '/' | '/dashboard' | '/gravity-demo' | '/universe-explorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GravityDemoRoute: typeof GravityDemoRoute
  UniverseExplorerRoute: typeof UniverseExplorerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe-explorer': {
      id: '/universe-explorer'
      path: '/universe-explorer'
      fullPath: '/universe-explorer'
      preLoaderRoute: typeof UniverseExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gravity-demo': {
      id: '/gravity-demo'
      path: '/gravity-demo'
      fullPath: '/gravity-demo'
      preLoaderRoute: typeof GravityDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GravityDemoRoute: GravityDemoRoute,
  UniverseExplorerRoute: UniverseExplorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
