/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseExplorerRealdataRouteImport } from './routes/universe-explorer-realdata'
import { Route as StyleLabRouteImport } from './routes/style-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCompleteRouteImport } from './routes/auth/complete'
import { Route as GameColonyColonyIdRouteImport } from './routes/game/colony/$colonyId'
import { Route as GameColonyColonyIdIndexRouteImport } from './routes/game/colony/$colonyId/index'
import { Route as GameColonyColonyIdShipyardRouteImport } from './routes/game/colony/$colonyId/shipyard'
import { Route as GameColonyColonyIdResourcesRouteImport } from './routes/game/colony/$colonyId/resources'
import { Route as GameColonyColonyIdResearch8RouteImport } from './routes/game/colony/$colonyId/research8'
import { Route as GameColonyColonyIdResearch7RouteImport } from './routes/game/colony/$colonyId/research7'
import { Route as GameColonyColonyIdResearch6RouteImport } from './routes/game/colony/$colonyId/research6'
import { Route as GameColonyColonyIdResearch5RouteImport } from './routes/game/colony/$colonyId/research5'
import { Route as GameColonyColonyIdResearch4RouteImport } from './routes/game/colony/$colonyId/research4'
import { Route as GameColonyColonyIdResearch3RouteImport } from './routes/game/colony/$colonyId/research3'
import { Route as GameColonyColonyIdResearch2RouteImport } from './routes/game/colony/$colonyId/research2'
import { Route as GameColonyColonyIdResearch1RouteImport } from './routes/game/colony/$colonyId/research1'
import { Route as GameColonyColonyIdFleetRouteImport } from './routes/game/colony/$colonyId/fleet'
import { Route as GameColonyColonyIdFacilitiesRouteImport } from './routes/game/colony/$colonyId/facilities'
import { Route as GameColonyColonyIdDefensesRouteImport } from './routes/game/colony/$colonyId/defenses'
import { Route as GameColonyColonyIdContractsRouteImport } from './routes/game/colony/$colonyId/contracts'

const UniverseExplorerRealdataRoute =
  UniverseExplorerRealdataRouteImport.update({
    id: '/universe-explorer-realdata',
    path: '/universe-explorer-realdata',
    getParentRoute: () => rootRouteImport,
  } as any)
const StyleLabRoute = StyleLabRouteImport.update({
  id: '/style-lab',
  path: '/style-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const GameColonyColonyIdRoute = GameColonyColonyIdRouteImport.update({
  id: '/game/colony/$colonyId',
  path: '/game/colony/$colonyId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameColonyColonyIdIndexRoute = GameColonyColonyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameColonyColonyIdRoute,
} as any)
const GameColonyColonyIdShipyardRoute =
  GameColonyColonyIdShipyardRouteImport.update({
    id: '/shipyard',
    path: '/shipyard',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResourcesRoute =
  GameColonyColonyIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch8Route =
  GameColonyColonyIdResearch8RouteImport.update({
    id: '/research8',
    path: '/research8',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch7Route =
  GameColonyColonyIdResearch7RouteImport.update({
    id: '/research7',
    path: '/research7',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch6Route =
  GameColonyColonyIdResearch6RouteImport.update({
    id: '/research6',
    path: '/research6',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch5Route =
  GameColonyColonyIdResearch5RouteImport.update({
    id: '/research5',
    path: '/research5',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch4Route =
  GameColonyColonyIdResearch4RouteImport.update({
    id: '/research4',
    path: '/research4',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch3Route =
  GameColonyColonyIdResearch3RouteImport.update({
    id: '/research3',
    path: '/research3',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch2Route =
  GameColonyColonyIdResearch2RouteImport.update({
    id: '/research2',
    path: '/research2',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdResearch1Route =
  GameColonyColonyIdResearch1RouteImport.update({
    id: '/research1',
    path: '/research1',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdFleetRoute = GameColonyColonyIdFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => GameColonyColonyIdRoute,
} as any)
const GameColonyColonyIdFacilitiesRoute =
  GameColonyColonyIdFacilitiesRouteImport.update({
    id: '/facilities',
    path: '/facilities',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdDefensesRoute =
  GameColonyColonyIdDefensesRouteImport.update({
    id: '/defenses',
    path: '/defenses',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)
const GameColonyColonyIdContractsRoute =
  GameColonyColonyIdContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => GameColonyColonyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/style-lab': typeof StyleLabRoute
  '/universe-explorer-realdata': typeof UniverseExplorerRealdataRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/game/colony/$colonyId': typeof GameColonyColonyIdRouteWithChildren
  '/game/colony/$colonyId/contracts': typeof GameColonyColonyIdContractsRoute
  '/game/colony/$colonyId/defenses': typeof GameColonyColonyIdDefensesRoute
  '/game/colony/$colonyId/facilities': typeof GameColonyColonyIdFacilitiesRoute
  '/game/colony/$colonyId/fleet': typeof GameColonyColonyIdFleetRoute
  '/game/colony/$colonyId/research1': typeof GameColonyColonyIdResearch1Route
  '/game/colony/$colonyId/research2': typeof GameColonyColonyIdResearch2Route
  '/game/colony/$colonyId/research3': typeof GameColonyColonyIdResearch3Route
  '/game/colony/$colonyId/research4': typeof GameColonyColonyIdResearch4Route
  '/game/colony/$colonyId/research5': typeof GameColonyColonyIdResearch5Route
  '/game/colony/$colonyId/research6': typeof GameColonyColonyIdResearch6Route
  '/game/colony/$colonyId/research7': typeof GameColonyColonyIdResearch7Route
  '/game/colony/$colonyId/research8': typeof GameColonyColonyIdResearch8Route
  '/game/colony/$colonyId/resources': typeof GameColonyColonyIdResourcesRoute
  '/game/colony/$colonyId/shipyard': typeof GameColonyColonyIdShipyardRoute
  '/game/colony/$colonyId/': typeof GameColonyColonyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/style-lab': typeof StyleLabRoute
  '/universe-explorer-realdata': typeof UniverseExplorerRealdataRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/game/colony/$colonyId/contracts': typeof GameColonyColonyIdContractsRoute
  '/game/colony/$colonyId/defenses': typeof GameColonyColonyIdDefensesRoute
  '/game/colony/$colonyId/facilities': typeof GameColonyColonyIdFacilitiesRoute
  '/game/colony/$colonyId/fleet': typeof GameColonyColonyIdFleetRoute
  '/game/colony/$colonyId/research1': typeof GameColonyColonyIdResearch1Route
  '/game/colony/$colonyId/research2': typeof GameColonyColonyIdResearch2Route
  '/game/colony/$colonyId/research3': typeof GameColonyColonyIdResearch3Route
  '/game/colony/$colonyId/research4': typeof GameColonyColonyIdResearch4Route
  '/game/colony/$colonyId/research5': typeof GameColonyColonyIdResearch5Route
  '/game/colony/$colonyId/research6': typeof GameColonyColonyIdResearch6Route
  '/game/colony/$colonyId/research7': typeof GameColonyColonyIdResearch7Route
  '/game/colony/$colonyId/research8': typeof GameColonyColonyIdResearch8Route
  '/game/colony/$colonyId/resources': typeof GameColonyColonyIdResourcesRoute
  '/game/colony/$colonyId/shipyard': typeof GameColonyColonyIdShipyardRoute
  '/game/colony/$colonyId': typeof GameColonyColonyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/style-lab': typeof StyleLabRoute
  '/universe-explorer-realdata': typeof UniverseExplorerRealdataRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/game/colony/$colonyId': typeof GameColonyColonyIdRouteWithChildren
  '/game/colony/$colonyId/contracts': typeof GameColonyColonyIdContractsRoute
  '/game/colony/$colonyId/defenses': typeof GameColonyColonyIdDefensesRoute
  '/game/colony/$colonyId/facilities': typeof GameColonyColonyIdFacilitiesRoute
  '/game/colony/$colonyId/fleet': typeof GameColonyColonyIdFleetRoute
  '/game/colony/$colonyId/research1': typeof GameColonyColonyIdResearch1Route
  '/game/colony/$colonyId/research2': typeof GameColonyColonyIdResearch2Route
  '/game/colony/$colonyId/research3': typeof GameColonyColonyIdResearch3Route
  '/game/colony/$colonyId/research4': typeof GameColonyColonyIdResearch4Route
  '/game/colony/$colonyId/research5': typeof GameColonyColonyIdResearch5Route
  '/game/colony/$colonyId/research6': typeof GameColonyColonyIdResearch6Route
  '/game/colony/$colonyId/research7': typeof GameColonyColonyIdResearch7Route
  '/game/colony/$colonyId/research8': typeof GameColonyColonyIdResearch8Route
  '/game/colony/$colonyId/resources': typeof GameColonyColonyIdResourcesRoute
  '/game/colony/$colonyId/shipyard': typeof GameColonyColonyIdShipyardRoute
  '/game/colony/$colonyId/': typeof GameColonyColonyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/style-lab'
    | '/universe-explorer-realdata'
    | '/auth/complete'
    | '/game/colony/$colonyId'
    | '/game/colony/$colonyId/contracts'
    | '/game/colony/$colonyId/defenses'
    | '/game/colony/$colonyId/facilities'
    | '/game/colony/$colonyId/fleet'
    | '/game/colony/$colonyId/research1'
    | '/game/colony/$colonyId/research2'
    | '/game/colony/$colonyId/research3'
    | '/game/colony/$colonyId/research4'
    | '/game/colony/$colonyId/research5'
    | '/game/colony/$colonyId/research6'
    | '/game/colony/$colonyId/research7'
    | '/game/colony/$colonyId/research8'
    | '/game/colony/$colonyId/resources'
    | '/game/colony/$colonyId/shipyard'
    | '/game/colony/$colonyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/style-lab'
    | '/universe-explorer-realdata'
    | '/auth/complete'
    | '/game/colony/$colonyId/contracts'
    | '/game/colony/$colonyId/defenses'
    | '/game/colony/$colonyId/facilities'
    | '/game/colony/$colonyId/fleet'
    | '/game/colony/$colonyId/research1'
    | '/game/colony/$colonyId/research2'
    | '/game/colony/$colonyId/research3'
    | '/game/colony/$colonyId/research4'
    | '/game/colony/$colonyId/research5'
    | '/game/colony/$colonyId/research6'
    | '/game/colony/$colonyId/research7'
    | '/game/colony/$colonyId/research8'
    | '/game/colony/$colonyId/resources'
    | '/game/colony/$colonyId/shipyard'
    | '/game/colony/$colonyId'
  id:
    | '__root__'
    | '/'
    | '/style-lab'
    | '/universe-explorer-realdata'
    | '/auth/complete'
    | '/game/colony/$colonyId'
    | '/game/colony/$colonyId/contracts'
    | '/game/colony/$colonyId/defenses'
    | '/game/colony/$colonyId/facilities'
    | '/game/colony/$colonyId/fleet'
    | '/game/colony/$colonyId/research1'
    | '/game/colony/$colonyId/research2'
    | '/game/colony/$colonyId/research3'
    | '/game/colony/$colonyId/research4'
    | '/game/colony/$colonyId/research5'
    | '/game/colony/$colonyId/research6'
    | '/game/colony/$colonyId/research7'
    | '/game/colony/$colonyId/research8'
    | '/game/colony/$colonyId/resources'
    | '/game/colony/$colonyId/shipyard'
    | '/game/colony/$colonyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StyleLabRoute: typeof StyleLabRoute
  UniverseExplorerRealdataRoute: typeof UniverseExplorerRealdataRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  GameColonyColonyIdRoute: typeof GameColonyColonyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe-explorer-realdata': {
      id: '/universe-explorer-realdata'
      path: '/universe-explorer-realdata'
      fullPath: '/universe-explorer-realdata'
      preLoaderRoute: typeof UniverseExplorerRealdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-lab': {
      id: '/style-lab'
      path: '/style-lab'
      fullPath: '/style-lab'
      preLoaderRoute: typeof StyleLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/colony/$colonyId': {
      id: '/game/colony/$colonyId'
      path: '/game/colony/$colonyId'
      fullPath: '/game/colony/$colonyId'
      preLoaderRoute: typeof GameColonyColonyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/colony/$colonyId/': {
      id: '/game/colony/$colonyId/'
      path: '/'
      fullPath: '/game/colony/$colonyId/'
      preLoaderRoute: typeof GameColonyColonyIdIndexRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/shipyard': {
      id: '/game/colony/$colonyId/shipyard'
      path: '/shipyard'
      fullPath: '/game/colony/$colonyId/shipyard'
      preLoaderRoute: typeof GameColonyColonyIdShipyardRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/resources': {
      id: '/game/colony/$colonyId/resources'
      path: '/resources'
      fullPath: '/game/colony/$colonyId/resources'
      preLoaderRoute: typeof GameColonyColonyIdResourcesRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research8': {
      id: '/game/colony/$colonyId/research8'
      path: '/research8'
      fullPath: '/game/colony/$colonyId/research8'
      preLoaderRoute: typeof GameColonyColonyIdResearch8RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research7': {
      id: '/game/colony/$colonyId/research7'
      path: '/research7'
      fullPath: '/game/colony/$colonyId/research7'
      preLoaderRoute: typeof GameColonyColonyIdResearch7RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research6': {
      id: '/game/colony/$colonyId/research6'
      path: '/research6'
      fullPath: '/game/colony/$colonyId/research6'
      preLoaderRoute: typeof GameColonyColonyIdResearch6RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research5': {
      id: '/game/colony/$colonyId/research5'
      path: '/research5'
      fullPath: '/game/colony/$colonyId/research5'
      preLoaderRoute: typeof GameColonyColonyIdResearch5RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research4': {
      id: '/game/colony/$colonyId/research4'
      path: '/research4'
      fullPath: '/game/colony/$colonyId/research4'
      preLoaderRoute: typeof GameColonyColonyIdResearch4RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research3': {
      id: '/game/colony/$colonyId/research3'
      path: '/research3'
      fullPath: '/game/colony/$colonyId/research3'
      preLoaderRoute: typeof GameColonyColonyIdResearch3RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research2': {
      id: '/game/colony/$colonyId/research2'
      path: '/research2'
      fullPath: '/game/colony/$colonyId/research2'
      preLoaderRoute: typeof GameColonyColonyIdResearch2RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/research1': {
      id: '/game/colony/$colonyId/research1'
      path: '/research1'
      fullPath: '/game/colony/$colonyId/research1'
      preLoaderRoute: typeof GameColonyColonyIdResearch1RouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/fleet': {
      id: '/game/colony/$colonyId/fleet'
      path: '/fleet'
      fullPath: '/game/colony/$colonyId/fleet'
      preLoaderRoute: typeof GameColonyColonyIdFleetRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/facilities': {
      id: '/game/colony/$colonyId/facilities'
      path: '/facilities'
      fullPath: '/game/colony/$colonyId/facilities'
      preLoaderRoute: typeof GameColonyColonyIdFacilitiesRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/defenses': {
      id: '/game/colony/$colonyId/defenses'
      path: '/defenses'
      fullPath: '/game/colony/$colonyId/defenses'
      preLoaderRoute: typeof GameColonyColonyIdDefensesRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
    '/game/colony/$colonyId/contracts': {
      id: '/game/colony/$colonyId/contracts'
      path: '/contracts'
      fullPath: '/game/colony/$colonyId/contracts'
      preLoaderRoute: typeof GameColonyColonyIdContractsRouteImport
      parentRoute: typeof GameColonyColonyIdRoute
    }
  }
}

interface GameColonyColonyIdRouteChildren {
  GameColonyColonyIdContractsRoute: typeof GameColonyColonyIdContractsRoute
  GameColonyColonyIdDefensesRoute: typeof GameColonyColonyIdDefensesRoute
  GameColonyColonyIdFacilitiesRoute: typeof GameColonyColonyIdFacilitiesRoute
  GameColonyColonyIdFleetRoute: typeof GameColonyColonyIdFleetRoute
  GameColonyColonyIdResearch1Route: typeof GameColonyColonyIdResearch1Route
  GameColonyColonyIdResearch2Route: typeof GameColonyColonyIdResearch2Route
  GameColonyColonyIdResearch3Route: typeof GameColonyColonyIdResearch3Route
  GameColonyColonyIdResearch4Route: typeof GameColonyColonyIdResearch4Route
  GameColonyColonyIdResearch5Route: typeof GameColonyColonyIdResearch5Route
  GameColonyColonyIdResearch6Route: typeof GameColonyColonyIdResearch6Route
  GameColonyColonyIdResearch7Route: typeof GameColonyColonyIdResearch7Route
  GameColonyColonyIdResearch8Route: typeof GameColonyColonyIdResearch8Route
  GameColonyColonyIdResourcesRoute: typeof GameColonyColonyIdResourcesRoute
  GameColonyColonyIdShipyardRoute: typeof GameColonyColonyIdShipyardRoute
  GameColonyColonyIdIndexRoute: typeof GameColonyColonyIdIndexRoute
}

const GameColonyColonyIdRouteChildren: GameColonyColonyIdRouteChildren = {
  GameColonyColonyIdContractsRoute: GameColonyColonyIdContractsRoute,
  GameColonyColonyIdDefensesRoute: GameColonyColonyIdDefensesRoute,
  GameColonyColonyIdFacilitiesRoute: GameColonyColonyIdFacilitiesRoute,
  GameColonyColonyIdFleetRoute: GameColonyColonyIdFleetRoute,
  GameColonyColonyIdResearch1Route: GameColonyColonyIdResearch1Route,
  GameColonyColonyIdResearch2Route: GameColonyColonyIdResearch2Route,
  GameColonyColonyIdResearch3Route: GameColonyColonyIdResearch3Route,
  GameColonyColonyIdResearch4Route: GameColonyColonyIdResearch4Route,
  GameColonyColonyIdResearch5Route: GameColonyColonyIdResearch5Route,
  GameColonyColonyIdResearch6Route: GameColonyColonyIdResearch6Route,
  GameColonyColonyIdResearch7Route: GameColonyColonyIdResearch7Route,
  GameColonyColonyIdResearch8Route: GameColonyColonyIdResearch8Route,
  GameColonyColonyIdResourcesRoute: GameColonyColonyIdResourcesRoute,
  GameColonyColonyIdShipyardRoute: GameColonyColonyIdShipyardRoute,
  GameColonyColonyIdIndexRoute: GameColonyColonyIdIndexRoute,
}

const GameColonyColonyIdRouteWithChildren =
  GameColonyColonyIdRoute._addFileChildren(GameColonyColonyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StyleLabRoute: StyleLabRoute,
  UniverseExplorerRealdataRoute: UniverseExplorerRealdataRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  GameColonyColonyIdRoute: GameColonyColonyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
